name: Deploy Static Site to Firebase Hosting  # ржПржЗ ржУржпрж╝рж╛рж░рзНржХржлрзНрж▓рзЛржЯрж┐рж░ ржПржХржЯрж┐ ржЕрж░рзНржержкрзВрж░рзНржг ржирж╛ржо

on:
  push:
    branches:
      - main  # ЁЯЪи ржЦрзБржм ржЧрзБрж░рзБрждрзНржмржкрзВрж░рзНржг: ржЖржкржирж╛рж░ GitHub рж░рж┐ржкрзЛржЬрж┐ржЯрж░рж┐рж░ ржорзВрж▓ ржмрзНрж░рж╛ржЮрзНржЪрзЗрж░ ржирж╛ржо ржжрж┐ржиред
              # ржПржЯрж┐ рж╕рж╛ржзрж╛рж░ржгржд 'main' ржЕржержмрж╛ 'master' рж╣ржпрж╝ред

jobs:
  deploy_static:  # ржПржЗ ржХрж╛ржЬрзЗрж░ ржПржХржЯрж┐ ржЖржЗржбрж┐
    runs-on: ubuntu-latest  # ржПржЯрж┐ GitHub-ржПрж░ ржПржХржЯрж┐ ржнрж╛рж░рзНржЪрзБржпрж╝рж╛рж▓ ржорзЗрж╢рж┐ржи ржпрзЗржЦрж╛ржирзЗ ржЖржкржирж╛рж░ ржЕрзНржпрж╛ржХрж╢ржи рж░рж╛ржи ржХрж░ржмрзЗ

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # ржЖржкржирж╛рж░ GitHub рж░рж┐ржкрзЛржЬрж┐ржЯрж░рж┐ ржерзЗржХрзЗ ржХрзЛржб ржбрж╛ржЙржирж▓рзЛржб ржХрж░ржмрзЗ

      # ЁЯЪи ржПржЗржЦрж╛ржирзЗ ржХрзЛржирзЛ Node.js рж╕рзЗржЯржЖржк, npm install ржмрж╛ npm run build ржХржорж╛ржирзНржбрзЗрж░ ржкрзНрж░ржпрж╝рзЛржЬржи ржирзЗржЗ,
      # ржХрж╛рж░ржг ржЖржкржирж╛рж░ ржУржпрж╝рзЗржмрж╕рж╛ржЗржЯржЯрж┐ рж╕ржорзНржкрзВрж░рзНржг рж╕рзНржЯрзНржпрж╛ржЯрж┐ржХ (HTML, CSS, JS) ржПржмржВ ржХрзЛржирзЛ ржмрж┐рж▓рзНржб ржкрзНрж░рж╕рзЗрж╕ ржирзЗржЗред

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0  # Firebase-ржПрж░ ржЕржлрж┐рж╕рж┐ржпрж╝рж╛рж▓ GitHub Action ржпрж╛ рж╣рзЛрж╕рзНржЯрж┐ржВ-ржП ржбрж┐ржкрзНрж▓ржпрж╝ ржХрж░рзЗ
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'  # GitHub ржжрзНржмрж╛рж░рж╛ рж╕рзНржмржпрж╝ржВржХрзНрж░рж┐ржпрж╝ржнрж╛ржмрзЗ рж╕рж░ржмрж░рж╛рж╣ ржХрж░рж╛ ржПржХржЯрж┐ ржмрж┐рж▓рзНржЯ-ржЗржи ржЯрзЛржХрзЗржи
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TANVIREMART }}' # ЁЯЪи ржЦрзБржм ржЧрзБрж░рзБрждрзНржмржкрзВрж░рзНржг:
                                                                                      # ржПржЯрж┐ рж╕рзЗржЗ GitHub Secret-ржПрж░ ржирж╛ржо ржпрж╛ ржЖржкржирж┐ рж╕рзНржЯрзЗржк рзи-ржП рждрзИрж░рж┐ ржХрж░рзЗржЫрж┐рж▓рзЗржиред
                                                                                      # ржЖржкржирж╛рж░ ржЖрж╕рж▓ Firebase Service Account Token ржПржЦрж╛ржирзЗ рж╕рж░рж╛рж╕рж░рж┐ ржжрзЗржмрзЗржи ржирж╛!
                                                                                      # рж╢рзБржзрзБ Secret-ржПрж░ ржирж╛ржоржЯрж┐ ржПржЦрж╛ржирзЗ ржерж╛ржХржмрзЗред
          projectId: 'tanviremart'  # ЁЯЪи ржЦрзБржм ржЧрзБрж░рзБрждрзНржмржкрзВрж░рзНржг: ржЖржкржирж╛рж░ Firebase ржкрзНрж░рзЛржЬрзЗржХрзНржЯрзЗрж░ ID ржжрж┐ржиред
                                    # (ржЖржкржирж╛рж░ ржжрзЗржУрзЯрж╛ рждржерзНржп ржЕржирзБржпрж╛рзЯрзА ржПржЯрж┐ 'tanviremart')
          channelId: 'live'  # ржПржЯрж┐ 'live' рж░рж╛ржЦрж╛ рж╣ржпрж╝ рж╕рж╛ржзрж╛рж░ржгржд ржкрзНрж░рзЛржбрж╛ржХрж╢ржи рж╕рж╛ржЗржЯрзЗрж░ ржЬржирзНржпред
                             # ржЪрж╛ржЗрж▓рзЗ ржЯрзЗрж╕рзНржЯрж┐ржВ ржПрж░ ржЬржирзНржп 'preview' ржмрж╛ ржЕржирзНржп ржХрзЛржирзЛ ржЪрзНржпрж╛ржирзЗрж▓ ржЖржЗржбрж┐ ржмрзНржпржмрж╣рж╛рж░ ржХрж░рждрзЗ ржкрж╛рж░рзЗржиред

          # entryPoint: '.'  # ржпржжрж┐ ржЖржкржирж╛рж░ `firebase.json` ржлрж╛ржЗрж▓ржЯрж┐ ржЖржкржирж╛рж░ рж░рж┐ржкрзЛржЬрж┐ржЯрж░рж┐рж░ рж░рзБржЯ ржбрж┐рж░рзЗржХрзНржЯрж░рж┐рждрзЗ ржерж╛ржХрзЗ,
                            # рждрж╛рж╣рж▓рзЗ ржПржЗ рж▓рж╛ржЗржиржЯрж┐ рж╕рж╛ржзрж╛рж░ржгржд ржжрж░ржХрж╛рж░ рж╣рзЯ ржирж╛ред
                            # ржпржжрж┐ ржПржЯрж┐ ржХрзЛржирзЛ рж╕рж╛ржм-ржбрж┐рж░рзЗржХрзНржЯрж░рж┐рждрзЗ ржерж╛ржХрзЗ, рждрж╛рж╣рж▓рзЗ рж╕рзЗржЗ ржбрж┐рж░рзЗржХрзНржЯрж░рж┐рж░ ржкрж╛рже ржПржЦрж╛ржирзЗ ржжрж┐рждрзЗ рж╣ржмрзЗред
